### PR TITLE
cleanup after transition is done

### PR DESCRIPTION
**Pull request by ev3nvy**

### CODE REVIEW

**Comment by ev3nvy** [comment]
Currently, while using `<Transition>` block in vue3, code mirror gets destroyed before the transition is finished. This happens because `onBeforeUnmount()` and `onUnmounted()` are called before transition actually finishes (see [vuejs/vue#6983](https://github.com/vuejs/vue/issues/6983) and [vuejs/core#994](https://github.com/vuejs/core/issues/994)).

This fix is based on https://github.com/diachedelic/vue-removed-hook-mixin, but not added as a dependency since mixins are deprecated in vue3 and the original is not based on typescript.

**Comment by surmon-china** [comment]
Hi @ev3nvy, I understand your need, but components shouldn't assume too much external environment, it's neither necessary nor desirable, so I think it might be possible to add a prop option like `autoDestroy` to the component to control whether the component should be automatically destroyed when `onBeforeUnmount`.

Also, you could control the CodeMirror destroy via the external `<Transition>` related event `onAfterLeave`.

It looks like this:

```vue
<template>
  <transition ... @afterLeave="handleTransitionLeave">
    <codemirror ... :auto-destroy="false" @ready="handleReady" />
  </transition>
</template>

<script>
  import { shallowRef } from "vue";
  import { Codemirror } from "vue-codemirror";

  export default {
    components: {
      Codemirror,
    },
    setup() {
      const view = shallowRef();
      const handleReady = (payload) => {
        view.value = payload.view;
      };

      const handleTransitionLeave = () => {
        view.value.destroy();
      };

      return {
        handleReady,
        handleTransitionLeave,
      };
    },
  };
</script>
```

**Comment by ev3nvy** [comment]
Agreed, this solution is better. I didn't use `afterLeave()` because I assumed that the developer could use something other than `<Transition>` or not use anything at all. This way we give control to the developer which means they could tackle some very specific problems without the need of opening a pr here.

Will you handle adding `autoDestroy`, or do you want me to open a pr?

**Comment by surmon-china** [comment]
I will release this new feature in the next version v6.0.1 as soon as possible.

**Comment by surmon-china** [comment]
@ev3nvy v6.0.1 has been released and now supports the [`autoDestroy` prop property](https://github.com/surmon-china/vue-codemirror#component-props).

**Pull request closed without merging**
